name: Build iOS App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Set up Flutter environment and use the desired version
    - name: Set up Flutter environment
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.5.2' # Set this to the required version

    # Step 3: Install Flutter dependencies
    - name: Install dependencies
      run: flutter pub get

    # Step 4: Set up CocoaPods (for iOS)
    - name: Install CocoaPods dependencies
      run: |
        cd ios
        pod install
      working-directory: ios

    # Step 5: Build the iOS app without signing
    - name: Build iOS without code signing
      run: flutter build ios --no-codesign

    # Step 6: Archive build artifacts
    - name: Archive build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ios-app
        path: build/ios/iphoneos
