name: Build iOS without Signing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_ios:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.5'  # You can specify the Flutter version

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Set up Ruby for CocoaPods
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '3.x'  # Or any Ruby version that works with your environment

      - name: Install CocoaPods dependencies
        run: |
          cd ios
          pod install

      - name: Build iOS App without Code Signing
        run: flutter build ios --release --no-codesign

      - name: Archive IPA
        run: |
          cd build/ios/iphoneos
          mkdir -p Payload
          cp -r Runner.app Payload/
          zip -r Runner.ipa Payload
        shell: bash

      - name: Upload IPA as artifact
        uses: actions/upload-artifact@v3
        with:
          name: Runner.ipa
          path: build/ios/iphoneos/Runner.ipa
