name: iOS Build without Signing

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.6'  # Ensure this version includes Dart 3.5.2

      - name: Set up Flutter
        run: flutter pub get

      - name: Install CocoaPods dependencies
        run: |
          cd ios
          pod install
        working-directory: ./ios

      - name: Build iOS without signing
        run: |
          flutter build ios --no-codesign

      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ios-build
          path: build/ios/ipa
