name: Build iOS App

on:
  push:
    branches:
      - main

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.10.6'  # Updated to 3.10.6

    - name: Install CocoaPods Dependencies
      run: |
        cd ios
        pod init
        pod install

    - name: Flutter clean
      run: flutter clean

    - name: Flutter pub get
      run: flutter pub get

    - name: Build iOS without code signing
      run: flutter build ios --no-codesign --release

    - name: Archive the iOS build
      run: |
        mkdir -p build/ios/ipa
        xcodebuild -workspace ios/Runner.xcworkspace \
          -scheme Runner \
          -sdk iphoneos \
          -configuration Release \
          archive -archivePath build/ios/archive/Runner.xcarchive

    - name: Export IPA
      run: |
        xcodebuild -exportArchive \
          -archivePath build/ios/archive/Runner.xcarchive \
          -exportOptionsPlist ios/Flutter/ExportOptions.plist \
          -exportPath build/ios/ipa

    - name: Upload IPA as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Runner.ipa
        path: build/ios/ipa/*.ipa
